// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameElement = "elements"

// Element mapped from table <elements>
type Element struct {
	ID   int32  `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Code string `gorm:"column:code;not null" json:"code"`
	Name string `gorm:"column:name;not null" json:"name"`
}

// TableName Element's table name
func (*Element) TableName() string {
	return TableNameElement
}
