// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameEvolutionsRule = "evolutions_rule"

// EvolutionsRule mapped from table <evolutions_rule>
type EvolutionsRule struct {
	ID    int32   `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Level *int32  `gorm:"column:level" json:"level"`
	Item  *string `gorm:"column:item" json:"item"`
}

// TableName EvolutionsRule's table name
func (*EvolutionsRule) TableName() string {
	return TableNameEvolutionsRule
}
