// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameMontersSkill = "monters_skills"

// MontersSkill mapped from table <monters_skills>
type MontersSkill struct {
	MonterID *int32 `gorm:"column:monter_id" json:"monter_id"`
	SkillID  *int32 `gorm:"column:skill_id" json:"skill_id"`
}

// TableName MontersSkill's table name
func (*MontersSkill) TableName() string {
	return TableNameMontersSkill
}
