// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameMontersEvolution = "monters_evolution"

// MontersEvolution mapped from table <monters_evolution>
type MontersEvolution struct {
	MonterID        int32 `gorm:"column:monter_id;not null" json:"monter_id"`
	EvolutionRuleID int32 `gorm:"column:evolution_rule_id;not null" json:"evolution_rule_id"`
}

// TableName MontersEvolution's table name
func (*MontersEvolution) TableName() string {
	return TableNameMontersEvolution
}
