// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameMonterElement = "monter_elements"

// MonterElement mapped from table <monter_elements>
type MonterElement struct {
	MonterID  int32 `gorm:"column:monter_id;not null" json:"monter_id"`
	ElementID int32 `gorm:"column:element_id;not null" json:"element_id"`
}

// TableName MonterElement's table name
func (*MonterElement) TableName() string {
	return TableNameMonterElement
}
