// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameMonter = "monters"

// Monter mapped from table <monters>
type Monter struct {
	ID       int32  `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Name     string `gorm:"column:name;not null" json:"name"`
	TypeID   *int32 `gorm:"column:type_id" json:"type_id"`
	GenderID *int32 `gorm:"column:gender_id" json:"gender_id"`
}

// TableName Monter's table name
func (*Monter) TableName() string {
	return TableNameMonter
}
