// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameSkillLearn = "skill_learn"

// SkillLearn mapped from table <skill_learn>
type SkillLearn struct {
	ID   int32  `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Name string `gorm:"column:name;not null" json:"name"`
}

// TableName SkillLearn's table name
func (*SkillLearn) TableName() string {
	return TableNameSkillLearn
}
