// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameSkill = "skills"

// Skill mapped from table <skills>
type Skill struct {
	ID              int32  `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Level           *int32 `gorm:"column:level" json:"level"`
	ElementID       int32  `gorm:"column:element_id;not null" json:"element_id"`
	SkillCategoryID int32  `gorm:"column:skill_category_id;not null" json:"skill_category_id"`
	Power           *int32 `gorm:"column:power" json:"power"`
	Accuracy        *int32 `gorm:"column:accuracy" json:"accuracy"`
	SkillLearnID    *int32 `gorm:"column:skill_learn_id" json:"skill_learn_id"`
}

// TableName Skill's table name
func (*Skill) TableName() string {
	return TableNameSkill
}
