// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameSkillCategory = "skill_category"

// SkillCategory mapped from table <skill_category>
type SkillCategory struct {
	ID   int32  `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Name string `gorm:"column:name;not null" json:"name"`
}

// TableName SkillCategory's table name
func (*SkillCategory) TableName() string {
	return TableNameSkillCategory
}
